# Generated by Django 5.0b1 on 2023-12-06 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelTable(
            name='company',
            table='Companies',
        ),
    ]
