# Generated by Django 5.0b1 on 2023-12-06 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_company_options_alter_company_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name_plural': 'Unit'},
        ),
        migrations.AlterModelTable(
            name='unit',
            table='Unit',
        ),
    ]
