# Generated by Django 5.0b1 on 2023-12-06 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_department_division'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='unit',
        ),
    ]
