# Generated by Django 5.0b1 on 2023-12-06 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_branch_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='unit',
        ),
        migrations.AddField(
            model_name='department',
            name='division',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.division'),
            preserve_default=False,
        ),
    ]
